/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { StakingPool, StakingPoolInterface } from "../../finance/StakingPool.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_stakingToken",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_rewardToken",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "initialOwner",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "OwnableInvalidOwner",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "OwnableUnauthorizedAccount",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "previousOwner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "OwnershipTransferred",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "renounceOwnership",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "rewardToken",
    "outputs": [
      {
        "internalType": "contract IERC20",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "stakingToken",
    "outputs": [
      {
        "internalType": "contract IERC20",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "transferOwnership",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080346100ea57601f61031838819003918201601f19168301916001600160401b038311848410176100ee578084926060946040528339810103126100ea5761004781610102565b90604061005660208301610102565b916001600160a01b0391829161006c9101610102565b169182156100d257815f549460018060a01b03199480868816175f558260405197167f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e05f80a3168360015416176001551690600254161760025561020190816101178239f35b604051631e4fbdf760e01b81525f6004820152602490fd5b5f80fd5b634e487b7160e01b5f52604160045260245ffd5b51906001600160a01b03821682036100ea5756fe60806040526004361015610011575f80fd5b5f3560e01c8063715018a61461013c57806372f702f3146101145780638da5cb5b146100ed578063f2fde38b1461007c5763f7c618c114610050575f80fd5b34610078575f366003190112610078576002546040516001600160a01b039091168152602090f35b5f80fd5b34610078576020366003190112610078576004356001600160a01b0381811691829003610078576100ab610180565b81156100d5575f548260018060a01b03198216175f55165f805160206101ac8339815191525f80a3005b604051631e4fbdf760e01b81525f6004820152602490fd5b34610078575f366003190112610078575f546040516001600160a01b039091168152602090f35b34610078575f366003190112610078576001546040516001600160a01b039091168152602090f35b34610078575f36600319011261007857610154610180565b5f80546001600160a01b0319811682556001600160a01b03165f805160206101ac8339815191528280a3005b5f546001600160a01b0316330361019357565b60405163118cdaa760e01b8152336004820152602490fdfe8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0a26469706673582212205b8ecd80221de3768d8625a32a4b7b1329874be47f7973c9bd6cffd4246f0c2a64736f6c63430008190033";

  
      type StakingPoolConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: StakingPoolConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class StakingPool__factory extends ContractFactory {
    
      constructor(...args: StakingPoolConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(_stakingToken: AddressLike, _rewardToken: AddressLike, initialOwner: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(_stakingToken, _rewardToken, initialOwner, overrides || {});
    };
    override deploy(_stakingToken: AddressLike, _rewardToken: AddressLike, initialOwner: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(_stakingToken, _rewardToken, initialOwner, overrides || {}) as Promise<StakingPool & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): StakingPool__factory {
      return super.connect(runner) as StakingPool__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): StakingPoolInterface {
      return new Interface(_abi) as StakingPoolInterface;
    }
    
    override attach(address: string | Addressable): StakingPool {
      return super.attach(address) as StakingPool;
    }
  static connect(address: string, runner?: ContractRunner | null): StakingPool {
      return new Contract(address, _abi, runner) as unknown as StakingPool;
    }
  }

  
  