/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ComplianceEnabled, ComplianceEnabledInterface } from "../../compliance/ComplianceEnabled.js";

  const _abi = [
  {
    "inputs": [],
    "name": "compliance",
    "outputs": [
      {
        "internalType": "contract TokenCompliance",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ComplianceEnabled__factory {
    static readonly abi = _abi;
    static createInterface(): ComplianceEnabledInterface {
      return new Interface(_abi) as ComplianceEnabledInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ComplianceEnabled {
      return new Contract(address, _abi, runner) as unknown as ComplianceEnabled;
    }
  }
  