/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'ComplianceEnabled', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ComplianceEnabled__factory>
getContractFactory(name: 'IdentityRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IdentityRegistry__factory>
getContractFactory(name: 'TokenCompliance', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TokenCompliance__factory>
getContractFactory(name: 'CommertizeToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CommertizeToken__factory>
getContractFactory(name: 'DividendVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.DividendVault__factory>
getContractFactory(name: 'ListingEscrow', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ListingEscrow__factory>
getContractFactory(name: 'StakingPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.StakingPool__factory>
getContractFactory(name: 'PropertyFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PropertyFactory__factory>
getContractFactory(name: 'PropertyToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PropertyToken__factory>
getContractFactory(name: 'PropertyTokenAdapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PropertyTokenAdapter__factory>
getContractFactory(name: 'PropertyTokenOFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PropertyTokenOFT__factory>

  getContractAt(name: 'ComplianceEnabled', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ComplianceEnabled>
getContractAt(name: 'IdentityRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IdentityRegistry>
getContractAt(name: 'TokenCompliance', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TokenCompliance>
getContractAt(name: 'CommertizeToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CommertizeToken>
getContractAt(name: 'DividendVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.DividendVault>
getContractAt(name: 'ListingEscrow', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ListingEscrow>
getContractAt(name: 'StakingPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.StakingPool>
getContractAt(name: 'PropertyFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PropertyFactory>
getContractAt(name: 'PropertyToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PropertyToken>
getContractAt(name: 'PropertyTokenAdapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PropertyTokenAdapter>
getContractAt(name: 'PropertyTokenOFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PropertyTokenOFT>

  deployContract(name: 'ComplianceEnabled', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ComplianceEnabled>
deployContract(name: 'IdentityRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IdentityRegistry>
deployContract(name: 'TokenCompliance', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenCompliance>
deployContract(name: 'CommertizeToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CommertizeToken>
deployContract(name: 'DividendVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DividendVault>
deployContract(name: 'ListingEscrow', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ListingEscrow>
deployContract(name: 'StakingPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StakingPool>
deployContract(name: 'PropertyFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyFactory>
deployContract(name: 'PropertyToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyToken>
deployContract(name: 'PropertyTokenAdapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyTokenAdapter>
deployContract(name: 'PropertyTokenOFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyTokenOFT>

  deployContract(name: 'ComplianceEnabled', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ComplianceEnabled>
deployContract(name: 'IdentityRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IdentityRegistry>
deployContract(name: 'TokenCompliance', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenCompliance>
deployContract(name: 'CommertizeToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CommertizeToken>
deployContract(name: 'DividendVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DividendVault>
deployContract(name: 'ListingEscrow', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ListingEscrow>
deployContract(name: 'StakingPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StakingPool>
deployContract(name: 'PropertyFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyFactory>
deployContract(name: 'PropertyToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyToken>
deployContract(name: 'PropertyTokenAdapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyTokenAdapter>
deployContract(name: 'PropertyTokenOFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyTokenOFT>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  