import {
	bytesToHex,
	ConsensusAggregationByFields,
	type CronPayload,
	cre,
	getNetwork,
	type HTTPSendRequester,
	median,
	type Runtime,
	TxStatus,
} from "@chainlink/cre-sdk";
import { type Address, encodeAbiParameters, type Hex, parseUnits } from "viem";
import { z } from "zod";
// Generated by the CRE CLI from the PropertyNavConsumer ABI — see cre/README.md
// ("Generate contract bindings"). Not checked in; run generation before simulate.
import { PropertyNavConsumer } from "./contracts/generated/PropertyNavConsumer";

/**
 * Commertize property-NAV oracle workflow.
 *
 * cron -> each DON node HTTP-fetches the NAV API -> nodes agree on the median
 * NAV -> the aggregated value is ABI-encoded, signed, and written to a
 * PropertyNavConsumer on each configured chain via the KeystoneForwarder.
 *
 * Report layout MUST match PropertyNavConsumer._processReport:
 *   (bytes32 propertyId, uint256 nav, uint32 timestamp)
 * NAV is scaled to 18 decimals.
 */

export const configSchema = z.object({
	// 6-field cron; min interval is 30s (CRE service quota). e.g. every 5 min.
	schedule: z.string(),
	// NAV/appraisal endpoint returning { navPerToken: number, asOf: string }.
	url: z.string(),
	// bytes32 property id, keying the NAV record in the consumer.
	propertyId: z.string(),
	// Per-chain consumer to write to. One workflow run fans out to all of them.
	evms: z.array(
		z.object({
			consumerAddress: z.string(),
			chainName: z.string(),
			gasLimit: z.string(),
			isTestnet: z.boolean(),
		})
	),
});

type Config = z.infer<typeof configSchema>;
type EVMConfig = z.infer<typeof configSchema.shape.evms.element>;

interface NavResponse {
	navPerToken: number;
	asOf: string;
}
// Only the fields we run consensus over. Keep numeric + Byzantine-robust.
interface NavInfo {
	nav: number;
}

// Runs on EACH node; results are aggregated by consensus (median) below.
const fetchNav = (sendRequester: HTTPSendRequester, config: Config): NavInfo => {
	const res = sendRequester
		.sendRequest({ method: "GET", url: config.url })
		.result();
	if (res.statusCode !== 200) {
		throw new Error(`NAV API returned HTTP ${res.statusCode}`);
	}
	const body: NavResponse = JSON.parse(
		Buffer.from(res.body).toString("utf-8")
	);
	if (typeof body.navPerToken !== "number" || !isFinite(body.navPerToken)) {
		throw new Error("NAV API returned a non-numeric navPerToken");
	}
	return { nav: body.navPerToken };
};

const writeNav = (
	evmConfig: EVMConfig,
	runtime: Runtime<Config>,
	navScaled: bigint,
	asOf: number
): void => {
	const network = getNetwork({
		chainFamily: "evm",
		chainSelectorName: evmConfig.chainName,
		isTestnet: evmConfig.isTestnet,
	});
	if (!network) throw new Error(`Unknown chain ${evmConfig.chainName}`);

	const evmClient = new cre.capabilities.EVMClient(
		network.chainSelector.selector
	);
	const consumer = new PropertyNavConsumer(
		evmClient,
		evmConfig.consumerAddress as Address
	);

	const encoded = encodeAbiParameters(
		[
			{ name: "propertyId", type: "bytes32" },
			{ name: "nav", type: "uint256" },
			{ name: "timestamp", type: "uint32" },
		],
		[runtime.config.propertyId as Hex, navScaled, asOf]
	);

	const resp = consumer.writeReport(runtime, encoded, {
		gasLimit: evmConfig.gasLimit,
	});
	if (resp.txStatus !== TxStatus.SUCCESS) {
		throw new Error(
			`NAV write to ${evmConfig.chainName} failed: ${
				resp.errorMessage || resp.txStatus
			}`
		);
	}
	runtime.log(
		`NAV write ok on ${evmConfig.chainName}: ${bytesToHex(
			resp.txHash || new Uint8Array(32)
		)}`
	);
};

const onCronTrigger = (
	runtime: Runtime<Config>,
	payload: CronPayload
): string => {
	if (!payload.scheduledExecutionTime) {
		throw new Error("missing scheduledExecutionTime");
	}
	// as-of time for the report; consumer enforces strictly-increasing.
	const asOf = Number(payload.scheduledExecutionTime);

	const http = new cre.capabilities.HTTPClient();
	const navInfo = http
		.sendRequest(
			runtime,
			fetchNav,
			ConsensusAggregationByFields<NavInfo>({ nav: median })
		)(runtime.config)
		.result();

	const navScaled = parseUnits(navInfo.nav.toString(), 18);
	for (const evm of runtime.config.evms) {
		writeNav(evm, runtime, navScaled, asOf);
	}
	return navInfo.nav.toString();
};

export function initWorkflow(config: Config) {
	const cron = new cre.capabilities.CronCapability();
	return [cre.handler(cron.trigger({ schedule: config.schedule }), onCronTrigger)];
}
