/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface DividendVaultInterface extends Interface {
    getFunction(nameOrSignature: "CLAIM_TIMEOUT" | "MAX_PROTOCOL_FEE_BPS" | "MIN_DISTRIBUTION" | "MIN_PROTOCOL_FEE_BPS" | "batchClaim" | "claim" | "depositDividend" | "distributionCounts" | "distributions" | "getClaimableAmount" | "getDistribution" | "hasClaimed" | "isValidProperty" | "owner" | "pause" | "paused" | "paymentToken" | "protocolFeeBps" | "protocolWallet" | "recoverUnclaimed" | "renounceOwnership" | "setPropertyValid" | "setProtocolFee" | "setProtocolWallet" | "transferOwnership" | "unpause"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DividendClaimed" | "DividendDeposited" | "OwnershipTransferred" | "Paused" | "PropertyValidated" | "ProtocolFeeUpdated" | "UnclaimedRecovered" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'CLAIM_TIMEOUT', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_PROTOCOL_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_DISTRIBUTION', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_PROTOCOL_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'batchClaim', values: [AddressLike, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'claim', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'depositDividend', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'distributionCounts', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'distributions', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getClaimableAmount', values: [AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getDistribution', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasClaimed', values: [AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isValidProperty', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'paymentToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'protocolFeeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'protocolWallet', values?: undefined): string;
encodeFunctionData(functionFragment: 'recoverUnclaimed', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setPropertyValid', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setProtocolFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setProtocolWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'CLAIM_TIMEOUT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_PROTOCOL_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_DISTRIBUTION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_PROTOCOL_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'batchClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositDividend', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distributionCounts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getClaimableAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDistribution', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isValidProperty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'protocolFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'protocolWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recoverUnclaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPropertyValid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setProtocolFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setProtocolWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
  }

  
    export namespace DividendClaimedEvent {
      export type InputTuple = [property: AddressLike, distributionId: BigNumberish, user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [property: string, distributionId: bigint, user: string, amount: bigint];
      export interface OutputObject {property: string, distributionId: bigint, user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DividendDepositedEvent {
      export type InputTuple = [property: AddressLike, distributionId: BigNumberish, amount: BigNumberish, snapshotId: BigNumberish];
      export type OutputTuple = [property: string, distributionId: bigint, amount: bigint, snapshotId: bigint];
      export interface OutputObject {property: string, distributionId: bigint, amount: bigint, snapshotId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PropertyValidatedEvent {
      export type InputTuple = [property: AddressLike, valid: boolean];
      export type OutputTuple = [property: string, valid: boolean];
      export interface OutputObject {property: string, valid: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProtocolFeeUpdatedEvent {
      export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
      export type OutputTuple = [oldFee: bigint, newFee: bigint];
      export interface OutputObject {oldFee: bigint, newFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnclaimedRecoveredEvent {
      export type InputTuple = [property: AddressLike, distributionId: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [property: string, distributionId: bigint, amount: bigint];
      export interface OutputObject {property: string, distributionId: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DividendVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): DividendVault;
    waitForDeployment(): Promise<this>;

    interface: DividendVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CLAIM_TIMEOUT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_PROTOCOL_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_DISTRIBUTION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_PROTOCOL_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    batchClaim: TypedContractMethod<
      [property: AddressLike, distributionIds: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    claim: TypedContractMethod<
      [property: AddressLike, distributionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    depositDividend: TypedContractMethod<
      [property: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    distributionCounts: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    distributions: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint] & {snapshotId: bigint, totalAmount: bigint, totalSupplyAtSnapshot: bigint, timestamp: bigint, totalClaimed: bigint }],
      'view'
    >
    

    
    getClaimableAmount: TypedContractMethod<
      [property: AddressLike, distributionId: BigNumberish, user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getDistribution: TypedContractMethod<
      [property: AddressLike, distributionId: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint] & {snapshotId: bigint, totalAmount: bigint, totalSupplyAtSnapshot: bigint, timestamp: bigint, totalClaimed: bigint }],
      'view'
    >
    

    
    hasClaimed: TypedContractMethod<
      [property: AddressLike, distributionId: BigNumberish, user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isValidProperty: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    paymentToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    protocolFeeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    protocolWallet: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recoverUnclaimed: TypedContractMethod<
      [property: AddressLike, distributionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setPropertyValid: TypedContractMethod<
      [property: AddressLike, valid: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setProtocolFee: TypedContractMethod<
      [_feeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setProtocolWallet: TypedContractMethod<
      [_wallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CLAIM_TIMEOUT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_PROTOCOL_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_DISTRIBUTION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_PROTOCOL_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'batchClaim'): TypedContractMethod<
      [property: AddressLike, distributionIds: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [property: AddressLike, distributionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositDividend'): TypedContractMethod<
      [property: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'distributionCounts'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'distributions'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint] & {snapshotId: bigint, totalAmount: bigint, totalSupplyAtSnapshot: bigint, timestamp: bigint, totalClaimed: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getClaimableAmount'): TypedContractMethod<
      [property: AddressLike, distributionId: BigNumberish, user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getDistribution'): TypedContractMethod<
      [property: AddressLike, distributionId: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint] & {snapshotId: bigint, totalAmount: bigint, totalSupplyAtSnapshot: bigint, timestamp: bigint, totalClaimed: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'hasClaimed'): TypedContractMethod<
      [property: AddressLike, distributionId: BigNumberish, user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isValidProperty'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'paymentToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'protocolFeeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'protocolWallet'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recoverUnclaimed'): TypedContractMethod<
      [property: AddressLike, distributionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPropertyValid'): TypedContractMethod<
      [property: AddressLike, valid: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setProtocolFee'): TypedContractMethod<
      [_feeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setProtocolWallet'): TypedContractMethod<
      [_wallet: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DividendClaimed'): TypedContractEvent<DividendClaimedEvent.InputTuple, DividendClaimedEvent.OutputTuple, DividendClaimedEvent.OutputObject>;
getEvent(key: 'DividendDeposited'): TypedContractEvent<DividendDepositedEvent.InputTuple, DividendDepositedEvent.OutputTuple, DividendDepositedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PropertyValidated'): TypedContractEvent<PropertyValidatedEvent.InputTuple, PropertyValidatedEvent.OutputTuple, PropertyValidatedEvent.OutputObject>;
getEvent(key: 'ProtocolFeeUpdated'): TypedContractEvent<ProtocolFeeUpdatedEvent.InputTuple, ProtocolFeeUpdatedEvent.OutputTuple, ProtocolFeeUpdatedEvent.OutputObject>;
getEvent(key: 'UnclaimedRecovered'): TypedContractEvent<UnclaimedRecoveredEvent.InputTuple, UnclaimedRecoveredEvent.OutputTuple, UnclaimedRecoveredEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'DividendClaimed(address,uint256,address,uint256)': TypedContractEvent<DividendClaimedEvent.InputTuple, DividendClaimedEvent.OutputTuple, DividendClaimedEvent.OutputObject>;
      DividendClaimed: TypedContractEvent<DividendClaimedEvent.InputTuple, DividendClaimedEvent.OutputTuple, DividendClaimedEvent.OutputObject>;
    

      'DividendDeposited(address,uint256,uint256,uint256)': TypedContractEvent<DividendDepositedEvent.InputTuple, DividendDepositedEvent.OutputTuple, DividendDepositedEvent.OutputObject>;
      DividendDeposited: TypedContractEvent<DividendDepositedEvent.InputTuple, DividendDepositedEvent.OutputTuple, DividendDepositedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PropertyValidated(address,bool)': TypedContractEvent<PropertyValidatedEvent.InputTuple, PropertyValidatedEvent.OutputTuple, PropertyValidatedEvent.OutputObject>;
      PropertyValidated: TypedContractEvent<PropertyValidatedEvent.InputTuple, PropertyValidatedEvent.OutputTuple, PropertyValidatedEvent.OutputObject>;
    

      'ProtocolFeeUpdated(uint256,uint256)': TypedContractEvent<ProtocolFeeUpdatedEvent.InputTuple, ProtocolFeeUpdatedEvent.OutputTuple, ProtocolFeeUpdatedEvent.OutputObject>;
      ProtocolFeeUpdated: TypedContractEvent<ProtocolFeeUpdatedEvent.InputTuple, ProtocolFeeUpdatedEvent.OutputTuple, ProtocolFeeUpdatedEvent.OutputObject>;
    

      'UnclaimedRecovered(address,uint256,uint256)': TypedContractEvent<UnclaimedRecoveredEvent.InputTuple, UnclaimedRecoveredEvent.OutputTuple, UnclaimedRecoveredEvent.OutputObject>;
      UnclaimedRecovered: TypedContractEvent<UnclaimedRecoveredEvent.InputTuple, UnclaimedRecoveredEvent.OutputTuple, UnclaimedRecoveredEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }