/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ListingEscrowInterface extends Interface {
    getFunction(nameOrSignature: "MIN_DEPOSIT" | "admin" | "adminBatchRefund" | "adminDistributeTokens" | "adminFinalize" | "deadline" | "deposit" | "depositFor" | "deposits" | "finalize" | "finalized" | "getAllInvestors" | "getInvestor" | "getInvestorCount" | "investors" | "owner" | "pause" | "paused" | "paymentToken" | "propertyToken" | "recoverTokens" | "refund" | "refunded" | "renounceOwnership" | "setAdmin" | "sponsor" | "targetRaise" | "totalRaised" | "transferOwnership" | "unpause"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AdminFinalized" | "AdminTokensDistributed" | "AdminUpdated" | "Deposited" | "Finalized" | "OwnershipTransferred" | "Paused" | "Refunded" | "TokensBurned" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'MIN_DEPOSIT', values?: undefined): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'adminBatchRefund', values: [AddressLike[]]): string;
encodeFunctionData(functionFragment: 'adminDistributeTokens', values: [AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'adminFinalize', values?: undefined): string;
encodeFunctionData(functionFragment: 'deadline', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'depositFor', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'deposits', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'finalize', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalized', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllInvestors', values?: undefined): string;
encodeFunctionData(functionFragment: 'getInvestor', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getInvestorCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'investors', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'paymentToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'propertyToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'recoverTokens', values?: undefined): string;
encodeFunctionData(functionFragment: 'refund', values?: undefined): string;
encodeFunctionData(functionFragment: 'refunded', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'sponsor', values?: undefined): string;
encodeFunctionData(functionFragment: 'targetRaise', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalRaised', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'MIN_DEPOSIT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'adminBatchRefund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'adminDistributeTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'adminFinalize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deadline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositFor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalized', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllInvestors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInvestor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInvestorCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'investors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propertyToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recoverTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refunded', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sponsor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'targetRaise', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRaised', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
  }

  
    export namespace AdminFinalizedEvent {
      export type InputTuple = [totalRaised: BigNumberish, timestamp: BigNumberish, admin: AddressLike];
      export type OutputTuple = [totalRaised: bigint, timestamp: bigint, admin: string];
      export interface OutputObject {totalRaised: bigint, timestamp: bigint, admin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AdminTokensDistributedEvent {
      export type InputTuple = [investor: AddressLike, amount: BigNumberish, admin: AddressLike];
      export type OutputTuple = [investor: string, amount: bigint, admin: string];
      export interface OutputObject {investor: string, amount: bigint, admin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AdminUpdatedEvent {
      export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike];
      export type OutputTuple = [oldAdmin: string, newAdmin: string];
      export interface OutputObject {oldAdmin: string, newAdmin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositedEvent {
      export type InputTuple = [investor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [investor: string, amount: bigint];
      export interface OutputObject {investor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FinalizedEvent {
      export type InputTuple = [totalRaised: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [totalRaised: bigint, timestamp: bigint];
      export interface OutputObject {totalRaised: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundedEvent {
      export type InputTuple = [investor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [investor: string, amount: bigint];
      export interface OutputObject {investor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensBurnedEvent {
      export type InputTuple = [amount: BigNumberish];
      export type OutputTuple = [amount: bigint];
      export interface OutputObject {amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ListingEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): ListingEscrow;
    waitForDeployment(): Promise<this>;

    interface: ListingEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MIN_DEPOSIT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    adminBatchRefund: TypedContractMethod<
      [investorList: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    adminDistributeTokens: TypedContractMethod<
      [investorList: AddressLike[], amounts: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    adminFinalize: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    deadline: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    depositFor: TypedContractMethod<
      [investor: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    deposits: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    finalize: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    finalized: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    getAllInvestors: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getInvestor: TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getInvestorCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    investors: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    paymentToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    propertyToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recoverTokens: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    refund: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    refunded: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setAdmin: TypedContractMethod<
      [_newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    sponsor: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    targetRaise: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalRaised: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MIN_DEPOSIT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'adminBatchRefund'): TypedContractMethod<
      [investorList: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'adminDistributeTokens'): TypedContractMethod<
      [investorList: AddressLike[], amounts: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'adminFinalize'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deadline'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'depositFor'): TypedContractMethod<
      [investor: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposits'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'finalize'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalized'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getAllInvestors'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getInvestor'): TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getInvestorCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'investors'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'paymentToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'propertyToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recoverTokens'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'refund'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'refunded'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAdmin'): TypedContractMethod<
      [_newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sponsor'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'targetRaise'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalRaised'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AdminFinalized'): TypedContractEvent<AdminFinalizedEvent.InputTuple, AdminFinalizedEvent.OutputTuple, AdminFinalizedEvent.OutputObject>;
getEvent(key: 'AdminTokensDistributed'): TypedContractEvent<AdminTokensDistributedEvent.InputTuple, AdminTokensDistributedEvent.OutputTuple, AdminTokensDistributedEvent.OutputObject>;
getEvent(key: 'AdminUpdated'): TypedContractEvent<AdminUpdatedEvent.InputTuple, AdminUpdatedEvent.OutputTuple, AdminUpdatedEvent.OutputObject>;
getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'Finalized'): TypedContractEvent<FinalizedEvent.InputTuple, FinalizedEvent.OutputTuple, FinalizedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'Refunded'): TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
getEvent(key: 'TokensBurned'): TypedContractEvent<TokensBurnedEvent.InputTuple, TokensBurnedEvent.OutputTuple, TokensBurnedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'AdminFinalized(uint256,uint256,address)': TypedContractEvent<AdminFinalizedEvent.InputTuple, AdminFinalizedEvent.OutputTuple, AdminFinalizedEvent.OutputObject>;
      AdminFinalized: TypedContractEvent<AdminFinalizedEvent.InputTuple, AdminFinalizedEvent.OutputTuple, AdminFinalizedEvent.OutputObject>;
    

      'AdminTokensDistributed(address,uint256,address)': TypedContractEvent<AdminTokensDistributedEvent.InputTuple, AdminTokensDistributedEvent.OutputTuple, AdminTokensDistributedEvent.OutputObject>;
      AdminTokensDistributed: TypedContractEvent<AdminTokensDistributedEvent.InputTuple, AdminTokensDistributedEvent.OutputTuple, AdminTokensDistributedEvent.OutputObject>;
    

      'AdminUpdated(address,address)': TypedContractEvent<AdminUpdatedEvent.InputTuple, AdminUpdatedEvent.OutputTuple, AdminUpdatedEvent.OutputObject>;
      AdminUpdated: TypedContractEvent<AdminUpdatedEvent.InputTuple, AdminUpdatedEvent.OutputTuple, AdminUpdatedEvent.OutputObject>;
    

      'Deposited(address,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'Finalized(uint256,uint256)': TypedContractEvent<FinalizedEvent.InputTuple, FinalizedEvent.OutputTuple, FinalizedEvent.OutputObject>;
      Finalized: TypedContractEvent<FinalizedEvent.InputTuple, FinalizedEvent.OutputTuple, FinalizedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'Refunded(address,uint256)': TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
      Refunded: TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
    

      'TokensBurned(uint256)': TypedContractEvent<TokensBurnedEvent.InputTuple, TokensBurnedEvent.OutputTuple, TokensBurnedEvent.OutputObject>;
      TokensBurned: TypedContractEvent<TokensBurnedEvent.InputTuple, TokensBurnedEvent.OutputTuple, TokensBurnedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }