/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface PropertyFactoryInterface extends Interface {
    getFunction(nameOrSignature: "deployEscrow" | "deployProperty" | "deployedEscrows" | "deployedProperties" | "getDeployedEscrows" | "getDeployedProperties" | "isEscrow" | "isPropertyToken" | "owner" | "renounceOwnership" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EscrowDeployed" | "OwnershipTransferred" | "PropertyDeployed"): EventFragment;

    encodeFunctionData(functionFragment: 'deployEscrow', values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'deployProperty', values: [string, string, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'deployedEscrows', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'deployedProperties', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDeployedEscrows', values?: undefined): string;
encodeFunctionData(functionFragment: 'getDeployedProperties', values?: undefined): string;
encodeFunctionData(functionFragment: 'isEscrow', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isPropertyToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'deployEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployProperty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployedEscrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployedProperties', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDeployedEscrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDeployedProperties', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isPropertyToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace EscrowDeployedEvent {
      export type InputTuple = [escrow: AddressLike, property: AddressLike, paymentToken: AddressLike, index: BigNumberish];
      export type OutputTuple = [escrow: string, property: string, paymentToken: string, index: bigint];
      export interface OutputObject {escrow: string, property: string, paymentToken: string, index: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PropertyDeployedEvent {
      export type InputTuple = [property: AddressLike, name: string, symbol: string, index: BigNumberish];
      export type OutputTuple = [property: string, name: string, symbol: string, index: bigint];
      export interface OutputObject {property: string, name: string, symbol: string, index: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PropertyFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): PropertyFactory;
    waitForDeployment(): Promise<this>;

    interface: PropertyFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    deployEscrow: TypedContractMethod<
      [propertyToken: AddressLike, paymentToken: AddressLike, sponsor: AddressLike, targetRaise: BigNumberish, deadline: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    deployProperty: TypedContractMethod<
      [name: string, symbol: string, supply: BigNumberish, compliance: AddressLike, ],
      [string],
      'nonpayable'
    >
    

    
    deployedEscrows: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    deployedProperties: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getDeployedEscrows: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getDeployedProperties: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    isEscrow: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isPropertyToken: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'deployEscrow'): TypedContractMethod<
      [propertyToken: AddressLike, paymentToken: AddressLike, sponsor: AddressLike, targetRaise: BigNumberish, deadline: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deployProperty'): TypedContractMethod<
      [name: string, symbol: string, supply: BigNumberish, compliance: AddressLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deployedEscrows'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'deployedProperties'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getDeployedEscrows'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getDeployedProperties'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'isEscrow'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isPropertyToken'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'EscrowDeployed'): TypedContractEvent<EscrowDeployedEvent.InputTuple, EscrowDeployedEvent.OutputTuple, EscrowDeployedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PropertyDeployed'): TypedContractEvent<PropertyDeployedEvent.InputTuple, PropertyDeployedEvent.OutputTuple, PropertyDeployedEvent.OutputObject>;

    filters: {
      
      'EscrowDeployed(address,address,address,uint256)': TypedContractEvent<EscrowDeployedEvent.InputTuple, EscrowDeployedEvent.OutputTuple, EscrowDeployedEvent.OutputObject>;
      EscrowDeployed: TypedContractEvent<EscrowDeployedEvent.InputTuple, EscrowDeployedEvent.OutputTuple, EscrowDeployedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PropertyDeployed(address,string,string,uint256)': TypedContractEvent<PropertyDeployedEvent.InputTuple, PropertyDeployedEvent.OutputTuple, PropertyDeployedEvent.OutputObject>;
      PropertyDeployed: TypedContractEvent<PropertyDeployedEvent.InputTuple, PropertyDeployedEvent.OutputTuple, PropertyDeployedEvent.OutputObject>;
    
    };
  }